export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
export const PROJECT_INIT = 'PROJECT_INIT';
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';
export const SET_PROJECT_SUCESS = 'SET_PROJECT_SUCESS';
export const SET_PROJECT_FAIL = 'SET_PROJECT_FAIL';

export const SET_SOURCE_ID = 'SET_SOURCE_ID';
export const SOURCE_INIT = 'SOURCE_INIT';
export const CREATE_SOURCE_START = 'CREATE_SOURCE_START';
export const CREATE_SOURCE_SUCCESS = 'CREATE_SOURCE_SUCCESS';
export const CREATE_SOURCE_FAIL = 'CREATE_SOURCE_FAIL';
export const VALIDATE_SOURCE_START = 'VALIDATE_SOURCE_START';
export const VALIDATE_SOURCE_SUCCESS = 'VALIDATE_SOURCE_SUCCESS';
export const VALIDATE_SOURCE_FAIL = 'VALIDATE_SOURCE_FAIL';
export const FETCH_SOURCES_START = 'FETCH_SOURCES_START';
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';
export const FETCH_SOURCES_FAIL = 'FETCH_SOURCES_FAIL';
